// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgAnimation/Interpolator>
#include <osgAnimation/Keyframe>
#include <osgAnimation/Sampler>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_ABSTRACT_OBJECT_REFLECTOR(osgAnimation::Sampler)
	I_DeclaringFile("osgAnimation/Sampler");
	I_BaseType(osg::Referenced);
	I_Constructor0(____Sampler,
	               "",
	               "");
	I_Method0(osgAnimation::KeyframeContainer *, getKeyframeContainer,
	          Properties::PURE_VIRTUAL,
	          __KeyframeContainer_P1__getKeyframeContainer,
	          "",
	          "");
	I_Method0(const osgAnimation::KeyframeContainer *, getKeyframeContainer,
	          Properties::PURE_VIRTUAL,
	          __C5_KeyframeContainer_P1__getKeyframeContainer,
	          "",
	          "");
	I_SimpleProperty(osgAnimation::KeyframeContainer *, KeyframeContainer, 
	                 __KeyframeContainer_P1__getKeyframeContainer, 
	                 0);
END_REFLECTOR

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::DoubleStepInterpolator >, osgAnimation::DoubleStepSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::FloatStepInterpolator >, osgAnimation::FloatStepSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::Vec2StepInterpolator >, osgAnimation::Vec2StepSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::Vec3StepInterpolator >, osgAnimation::Vec3StepSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::Vec4StepInterpolator >, osgAnimation::Vec4StepSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::QuatStepInterpolator >, osgAnimation::QuatStepSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::DoubleLinearInterpolator >, osgAnimation::DoubleLinearSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::FloatLinearInterpolator >, osgAnimation::FloatLinearSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::Vec2LinearInterpolator >, osgAnimation::Vec2LinearSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::Vec3LinearInterpolator >, osgAnimation::Vec3LinearSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::Vec4LinearInterpolator >, osgAnimation::Vec4LinearSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::QuatSphericalLinearInterpolator >, osgAnimation::QuatSphericalLinearSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::MatrixLinearInterpolator >, osgAnimation::MatrixLinearSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::FloatCubicBezierInterpolator >, osgAnimation::FloatCubicBezierSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::DoubleCubicBezierInterpolator >, osgAnimation::DoubleCubicBezierSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::Vec2CubicBezierInterpolator >, osgAnimation::Vec2CubicBezierSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::Vec3CubicBezierInterpolator >, osgAnimation::Vec3CubicBezierSampler)

TYPE_NAME_ALIAS(osgAnimation::TemplateSampler< osgAnimation::Vec4CubicBezierInterpolator >, osgAnimation::Vec4CubicBezierSampler)

